version: '3'

volumes:
  mysql_data:

networks:
  php_course:
    
services:
  web:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./apache/conf:/etc/apache2/sites-available
      - ./apache/php/php.ini:/usr/local/etc/php/php.ini
      
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    env_file:
      - .env
    restart: always
    networks:
      - php_course
      
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/scripts
    environment:
      - MYSQL_DATABASE=invoice_app
      - MYSQL_ROOT_PASSWORD=test
    networks:
      - php_course
    restart: always